version: '3.2'
services:
    nicos-cache:
       image: pshcyrill/nicos-cache:latest
       network_mode: host
       ports:
        - "14869:14869"
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/usr/src/nicos/log
       environment:
        - INSTRUMENT=nicos_pnpi.demo
    nicos-daemon:
       image: pshcyrill/nicos-daemon:latest
       network_mode: host
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./log:/usr/src/nicos/log
       environment:
        - INSTRUMENT=nicos_pnpi.demo
    nicos-poller:
       image: pshcyrill/nicos-poller:latest
       network_mode: host
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./data:/data
        - ./log:/usr/src/nicos/log
       environment:
        - INSTRUMENT=nicos_pnpi.demo
    nicos-elog:
       image: pshcyrill/nicos-elog:latest
       network_mode: host
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
        - ./data:/data
        - ./log:/usr/src/nicos/log
       environment:
        - INSTRUMENT=nicos_pnpi.demo
