version: '3.2'
services:
    nicos-cache:
       image: pshcyrill/nicos-cache:latest
       network_mode: host
       ports:
        - "14869:14869"
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
       environment:
        - INSTRUMENT=nicos_pnpi.demo
    nicos-daemon:
       image: pshcyrill/nicos-daemon:latest
       network_mode: host
       volumes:
        - ./nicos_pnpi:/usr/src/nicos/nicos_pnpi
       environment:
        - INSTRUMENT=nicos_pnpi.demo